<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class ClaudeService
{
    private $apiKey;
    private $apiBase = 'https://api.anthropic.com/v1';
    private $model = 'claude-3-5-sonnet-20241022';

    public function __construct()
    {
        $this->apiKey = env('ANTHROPIC_API_KEY');
    }

    /**
     * Review pull request using Claude AI
     */
    public function reviewPullRequest(array $prData, string $filteredDiff, array $files): ?array
    {
        if (!$this->apiKey) {
            Log::error('Anthropic API key not configured');
            return null;
        }

        $prompt = $this->buildReviewPrompt($prData, $filteredDiff, $files);

        try {
            $response = Http::withHeaders([
                'x-api-key' => $this->apiKey,
                'anthropic-version' => '2023-06-01',
                'content-type' => 'application/json',
            ])->timeout(120)->post("{$this->apiBase}/messages", [
                'model' => $this->model,
                'max_tokens' => 4096,
                'messages' => [
                    [
                        'role' => 'user',
                        'content' => $prompt,
                    ],
                ],
            ]);

            if ($response->successful()) {
                $data = $response->json();
                return [
                    'review' => $data['content'][0]['text'] ?? '',
                    'usage' => $data['usage'] ?? [],
                ];
            }

            Log::error('Failed to get Claude review', [
                'status' => $response->status(),
                'body' => $response->body(),
            ]);

            return null;
        } catch (\Exception $e) {
            Log::error('Exception calling Claude API', ['error' => $e->getMessage()]);
            return null;
        }
    }

    /**
     * Build review prompt for Claude
     */
    private function buildReviewPrompt(array $prData, string $diff, array $files): string
    {
        $filesList = implode("\n", array_map(function ($file) {
            $status = $file['status'] ?? 'modified';
            $additions = $file['additions'] ?? 0;
            $deletions = $file['deletions'] ?? 0;
            return "- {$file['filename']} ({$status}, +{$additions}/-{$deletions})";
        }, $files));

        return <<<PROMPT
You are a senior software engineer conducting a code review for a pull request.

## Pull Request Information
**Title:** {$prData['title']}
**Author:** {$prData['author']}
**Description:**
{$prData['description']}

**Base Branch:** {$prData['base']}
**Head Branch:** {$prData['head']}

## Files Changed ({$prData['changed_files']} files)
{$filesList}

## Diff (Sensitive data has been masked)
```diff
{$diff}
```

## Review Instructions
Please provide a comprehensive code review focusing on:

1. **Code Quality**
   - Code organization and structure
   - Naming conventions and readability
   - Code duplication
   - Complexity and maintainability

2. **Best Practices**
   - Design patterns usage
   - SOLID principles
   - DRY (Don't Repeat Yourself)
   - Error handling

3. **Security**
   - Input validation
   - SQL injection risks
   - XSS vulnerabilities
   - Authentication/Authorization issues
   - Note: Sensitive data has been masked, but review for any remaining security concerns

4. **Performance**
   - Potential bottlenecks
   - Database query optimization
   - Resource usage

5. **Testing**
   - Test coverage
   - Edge cases
   - Error scenarios

6. **Documentation**
   - Code comments
   - API documentation
   - README updates

## Output Format
Please structure your review as follows:

### Summary
[Brief overview of the changes and overall assessment]

### Strengths
[What's done well in this PR]

### Issues Found
[List critical issues, if any]

### Suggestions
[Improvements and recommendations]

### Security Notes
[Security-related observations]

### Final Recommendation
- [ ] Approve
- [ ] Request Changes
- [ ] Comment Only

**Note:** This review is automated using Claude AI. Please use human judgment for final decisions.
PROMPT;
    }

    /**
     * Format review for GitHub comment
     */
    public function formatReviewForGitHub(string $review, array $filterSummary): string
    {
        $maskedInfo = $filterSummary['masked_lines'] > 0
            ? "\n\n> **Note:** {$filterSummary['masked_lines']} lines containing sensitive data were masked during review."
            : '';

        return <<<COMMENT
## 🤖 Claude AI Code Review

{$review}

---
*This review was automatically generated by Claude AI*{$maskedInfo}
*Review Statistics: {$filterSummary['reviewed_lines']} lines reviewed*
COMMENT;
    }
}
